arctic_dashboard:
    resource: "@ArcticDashboardBundle/Controller/"
    type:     annotation
    prefix:   /

arctic_ticket:
    resource: "@ArcticTicketBundle/Controller/"
    type:     annotation
    prefix:   /

ArcticUserBundle:
    resource: "@ArcticUserBundle/Resources/config/routing.yml"

ArcticAssetBundle:
    resource: "@ArcticAssetBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
